### ISSUE TITLE
Traceback error ( AttributeError: 'str' object has no attribute 'decode')

### ISSUE THREAD

**Issue by jcm4atx** [shaarli/python-shaarli-client#51]
Python 3.7.3

When I enter `shaarli get-info` (or really any valid command) I get this:

Traceback (most recent call last):
  File "/home/pi/.virtualenvs/shaarli/bin/shaarli", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/shaarli_client/main.py", line 58, in main
    response = ShaarliV1Client(url, secret).request(args)
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/shaarli_client/client/v1.py", line 267, in request
    return self._request(* self._retrieve_http_params(args))
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/shaarli_client/client/v1.py", line 261, in _request
    params=params
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/requests/models.py", line 551, in prepare_auth
    r = auth(self)
  File "/home/pi/.virtualenvs/shaarli/lib/python3.7/site-packages/requests_jwt/__init__.py", line 165, in __call__
    request.headers['Authorization'] = self._header_format % token.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'

I do have the correct secret and URL of my instance.

**Comment by RebelPhoton** [comment]
I'm running into the same problem using python 3.6.13.

I've installed by running:

```
pyenv install 3.6.13
pipx install --python /home/daniel/.pyenv/versions/3.6.13/bin/python shaarli-client
nano ~/.config/shaarli/client.ini
```

```client.ini
[shaarli]
url = https://xxxxxxxxxxxx.org
secret = xxxxxxxxxxxx
```
```
$shaarli  get-info
Traceback (most recent call last):
  File "/home/daniel/.local/bin/shaarli", line 8, in <module>
    sys.exit(main())
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/shaarli_client/main.py", line 58, in main
    response = ShaarliV1Client(url, secret).request(args)
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/shaarli_client/client/v1.py", line 267, in request
    return self._request(* self._retrieve_http_params(args))
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/shaarli_client/client/v1.py", line 261, in _request
    params=params
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/requests/models.py", line 551, in prepare_auth
    r = auth(self)
  File "/home/daniel/.local/pipx/venvs/shaarli-client/lib/python3.6/site-packages/requests_jwt/__init__.py", line 165, in __call__
    request.headers['Authorization'] = self._header_format % token.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by RebelPhoton** [comment]
Hmm finally working with 3.5.10, using pip instead of pipx. And I have to run the absolute path:

`/home/daniel/.pyenv/versions/3.5.10/bin/shaarli get-info`

this way it works

**Comment by mrrcollins** [comment]
I'm seeing the same issue with Python 3.8.5 (Ubuntu 20.04):

```
Traceback (most recent call last):
  File "/home/goz/.virtualenvs/shaarli/bin/shaarli", line 8, in <module>
    sys.exit(main())
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/shaarli_client/main.py", line 58, in main
    response = ShaarliV1Client(url, secret).request(args)
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/shaarli_client/client/v1.py", line 267, in request
    return self._request(* self._retrieve_http_params(args))
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/shaarli_client/client/v1.py", line 257, in _request
    return requests.request(
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/requests/models.py", line 551, in prepare_auth
    r = auth(self)
  File "/home/goz/.virtualenvs/shaarli/lib/python3.8/site-packages/requests_jwt/__init__.py", line 165, in __call__
    request.headers['Authorization'] = self._header_format % token.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

I get the same error when I try to pass the url of the instance and the secret on the commandline.

**Comment by mrrcollins** [comment]
> Hmm finally working with 3.5.10, using pip instead of pipx. And I have to run the absolute path:
> 
> `/home/daniel/.pyenv/versions/3.5.10/bin/shaarli get-info`
> 
> this way it works

Good call. I linked that to /usr/local/bin/shaarli so I don't have to use the full path.

**Comment by nodiscc** [comment]
I can't reproduce this with Python 3.7.3 and the latest python-shaarli-client from `master`

```bash
$ shaarli get-info
{
    "global_counter": 4577,
    "private_counter": 155,
    "settings": {
        "default_private_links": false,
        "enabled_plugins": [
...
```


@jcm4atx @RebelPhoton @mrrcollins can you try installing [from source code](https://python-shaarli-client.readthedocs.io/en/latest/user/installation.html#from-the-source-code) and tell me if it works?

It should work on Python 3.6, it works for me on 3.7.3 (but we should add tests for 3.7), and it _might_ work on Python 3.8.

Python 3.4 and 3.5 are [not supported anymore](https://github.com/shaarli/python-shaarli-client/pull/52/commits/593debf50498c3f9db8601e524c1e4e2df207a3e)

**Comment by sebw** [comment]
Same problem on Fedora 34 and pip install, regardless of providing full path or not.

Python 3.9.4

```
$ shaarli get-info
Traceback (most recent call last):
  File "/home/sw/.local/bin/shaarli", line 8, in <module>
    sys.exit(main())
  File "/home/sw/.local/lib/python3.9/site-packages/shaarli_client/main.py", line 58, in main
    response = ShaarliV1Client(url, secret).request(args)
  File "/home/sw/.local/lib/python3.9/site-packages/shaarli_client/client/v1.py", line 267, in request
    return self._request(* self._retrieve_http_params(args))
  File "/home/sw/.local/lib/python3.9/site-packages/shaarli_client/client/v1.py", line 257, in _request
    return requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 551, in prepare_auth
    r = auth(self)
  File "/home/sw/.local/lib/python3.9/site-packages/requests_jwt/__init__.py", line 165, in __call__
    request.headers['Authorization'] = self._header_format % token.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by uriel1998** [comment]
Likewise, Debian bullseye/sid, Python 3.9.2, installed in venv 

```
steven@bunyip:$ ./shaarli get-info
Traceback (most recent call last):
  File "/home/steven/apps/shaarli/bin/./shaarli", line 8, in <module>
    sys.exit(main())
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/shaarli_client/main.py", line 58, in main
    response = ShaarliV1Client(url, secret).request(args)
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/shaarli_client/client/v1.py", line 267, in request
    return self._request(* self._retrieve_http_params(args))
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/shaarli_client/client/v1.py", line 257, in _request
    return requests.request(
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/requests/models.py", line 320, in prepare
    self.prepare_auth(auth, url)
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/requests/models.py", line 551, in prepare_auth
    r = auth(self)
  File "/home/steven/apps/shaarli/lib/python3.9/site-packages/requests_jwt/__init__.py", line 165, in __call__
    request.headers['Authorization'] = self._header_format % token.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
(shaarli) 
```

**Comment by sebw** [comment]
@nodiscc yes, it works for me (fedora 34)

**Comment by virtualtam** [comment]
Thanks for the feedback! I've merged the corresponding PRs and cut a new release that is available on PyPI, [v0.4.1](https://github.com/shaarli/python-shaarli-client/releases/tag/v0.4.1)
